[changelog]
header = ""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% for group, commits in commits | group_by(attribute="group") %}
    #### {{ group | upper_first }}
    {%- for commit in commits %}
        - {{ commit.message | upper_first | trim }}\
            {% if commit.github.username %} by @{{ commit.github.username }}{%- endif -%}
            {% if commit.github.pr_number %} in \
              [#{{ commit.github.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.github.pr_number }}) \
            {%- endif -%}
    {% endfor %}
{% endfor %}
"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
    # remove issue numbers from commits
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
    { message = "^perf", group = "<!-- 3 -->⚡ Performance" },
    { message = "^docs", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore|^ci", skip = true },
    { message = "^revert", group = "<!-- 5 -->◀️ Revert" },
]
sort_commits = "oldest"

[bump]
initial_tag = "0.1.0"

[remote.github]
owner = "biomejs"
repo = "biome-vscode"