# This workflow is responsible for publishing a prerelease version of the extension
# to the Visual Studio Marketplace, the Open VSX Registry. It is triggered 
# manually by the user.

name: ~Publish prerelease

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  package:
    name: Package
    uses: ./.github/workflows/~package-prerelease.yaml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
  publish-to-vs-marketplace:
    needs: [package]
    name: Publish to Visual Studio Marketplace
    uses: ./.github/workflows/~publish-to-vs-marketplace.yaml
    secrets: inherit
  publish-to-ovsx-registry:
    needs: [package]
    name: Publish to Open VSX Registry
    uses: ./.github/workflows/~publish-to-ovsx-registry.yaml
    secrets: inherit